### ISSUE TITLE
微调导入模块失败

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-Finetune#1]
微调测试bash scripts/finetune_chid_large.sh导入模块失败，没有以下两个文件：
from .gpt2_modeling_qa_cls import QAGPT2Model
from .gpt2_modeling_all_attn import AllAttnGPT2Model

注释掉之后缺失：QAGPT2Model
from model import GPT2Model, QAGPT2Model
以上缺失是否不需要

**Comment by zhenhao-huang** [comment]
我自己下载了CHID数据集放进目录下运行
tokenizer = GPT2Tokenizer(os.path.join(args.tokenizer_path, 'vocab.json'), os.path.join(args.tokenizer_path, 'merges.txt'), os.path.join(args.tokenizer_path, 'chinese_vocab.model'))
分词这块显示vocab.json，merges.txt，chinese_vocab.model这些都是缺失的，还是要用bpe的分词结果？

**Comment by zmingshi** [comment]
@zhenhao-huang  vocab.json chinese_vocab.model cpm_generature 那个项目中有，不过这个merges.txt 没找到，你解决了吗？

**Comment by zhenhao-huang** [comment]
> @zhenhao-huang vocab.json chinese_vocab.model cpm_generature 那个项目中有，不过这个merges.txt 没找到，你解决了吗？

没有，可能是要自己做分词

**Comment by t1101675** [comment]
模型导入模块的问题已经修复，不需要缺失的那几个模块。tokenizer的问题也已经解决，使用了新版本的分词，在bpe_3w_new中

**Comment by zhenhao-huang** [comment]
> 模型导入模块的问题已经修复，不需要缺失的那几个模块。tokenizer的问题也已经解决，使用了新版本的分词，在bpe_3w_new中

微调测试bash scripts/finetune_chid_small.sh报错，需要join() argument must be str or bytes, not 'int'
Epoch: 0, Global step: 3, Acc: 0.5
 0%|                                                                                                                                        |2/288578[01:12<2903:06:19,36.22s/it]
Traceback (most recent call last):
  File "finetune_chid.py", line 360, in <module>
    main()
  File "finetune_chid.py", line 329, in main
    save_checkpoint(global_step, model, optimizer, lr_scheduler, args)
  File "/home/klein/Desktop/CPM/CPM-Finetune/utils.py", line 183, in save_checkpoint
    save_ds_checkpoint(iteration, model, args)
  File "/home/klein/Desktop/CPM/CPM-Finetune/utils.py", line 242, in save_ds_checkpoint
    model.save_checkpoint(args.save, iteration, client_state = sd)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 1490, in save_checkpoint
    self._save_checkpoint(save_dir, tag, client_state=client_state)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 1531, in _save_checkpoint
    self._curr_ckpt_path = os.path.join(save_dir, tag)
  File "/home/klein/anaconda3/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/klein/anaconda3/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
这个错误把iteration改为str(iteration)就可以了吗？

我设置了batch为1，每训练3次就进行一次验证？，似乎这样速度很慢

**Comment by t1101675** [comment]
针对上面提到的那个报错，我们觉得是 deepspeed 版本的问题。我们在 README.md 中添加了我们使用的版本。对于训练参数的问题，可以根据需要自行调整，现在脚本里面已经更新成我们在训练时候使用的 log 和 eval 步数。

**Comment by zhenhao-huang** [comment]
是的，我用的是deepspeed 0.3.8版本，这个版本用的是os.path.join(save_dir, tag)，以往是os.path.dirname(save_path)就正常了，deepspeed 0.3.7可正常使用，感谢回复

**Comment by lulu51230** [comment]
您好， 您在微调小模型bash scripts/finetune_chid_small.sh ，请问一下，这个小模型在哪里下载的呀？
我只找到最大的CPM模型下载。还是说，可以用小模型参数微调预训练的大模型？

**Comment by zhenhao-huang** [comment]
@lulu51230 large模型对应CPM模型，small模型和medium模型应该是没放出来，但是可以直接微调，没加载模型用的是默认的gpt2模型，也可以通过加载CPM模型去跑small模型和medium模型

**Comment by lulu51230** [comment]
加载CPM模型去跑small模型和medium模型是如何做到的呢？large模型的词向量维度、layer层数等参数的大小与small模型和medium模型定义的不同呀？

**Comment by zhenhao-huang** [comment]
@lulu51230 加载CPM模型去跑small模型和medium模型我是仅仅修改large的层数，其他没改，这种做法我也不清楚是否可行）。如果只是测试的话，可以用默认的gpt2模型测试。
