### ISSUE TITLE
在加载CPM模型(26亿参数)的情况下，修改微调参数减小显存占用

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-Finetune#12]
CPM模型的原参数是：

- MPSIZE=2
- NLAYERS=32
- NHIDDEN=2560
- NATT=32
- MAXSEQLEN=1024

1.在两张3090显卡上跑不动，所以我尝试减小NLAYERS的层数，相当于减小了模型参数，可以跑得通，这样做会不会对微调结果有影响？如果有影响，怎么使其影响最小？
2.除了限制输入序列的长度，还有什么方法可以减小显存占用？
3.怎么使用CPU_offload？

**Comment by t1101675** [comment]
我们现在使用了 deepspeed 的 activation checkpointing 来减少显存占用，效果比较明显，您可以再尝试一下。

**Comment by zhenhao-huang** [comment]
@t1101675 启用deepspeed 的 activation checkpointing在两张3090显卡上对减少显存占用似乎没什么效果，但是不使用`fp16`精度，使用`fp32`精度对显存减小较明显。使用了`finetune_chid_large_fp32.sh`脚本之后，跑通large模型由原来的22层增加到28层，使用原参数的32层还是会溢出，感谢`finetune_chid_large_fp32.sh`脚本

**Comment by t1101675** [comment]
如果 batch size 都开到 1 了的话可能就还是不太行。减少层数这个操作我们也没有试过，但感觉和一些模型蒸馏时候用大模型参数进行初始化的操作比较相似，感觉可以参考相关工作如 [](https://arxiv.org/abs/1908.09355) 来选择删掉哪些层。

**Comment by zhenhao-huang** [comment]
好的，谢谢。我通过限制输入训练的长度，在我的数据集上能达到30层，我想尝试下开启cpu_offload来减少显存占用，这个需要怎么开启？cpu_offload似乎是在：
`[config.py:709:print]   zero_config .................. {
    "allgather_bucket_size": 500000000,
    "allgather_partitions": true,
    "contiguous_gradients": false,
    "cpu_offload": false,
    "elastic_checkpoint": true,
    "load_from_fp32_weights": false,
    "overlap_comm": false,
    "reduce_bucket_size": 500000000,
    "reduce_scatter": true,
    "stage": 2
}
`

**Comment by t1101675** [comment]
cpu_offload 的这个问题我们也在尝试，之后有了明确的结论会及时更新

**Comment by lichen222** [comment]
> 我们现在使用了 deepspeed 的 activation checkpointing 来减少显存占用，效果比较明显，您可以再尝试一下。

开发者您好，请问减少了NLAYERS为什么还能将large模型加载成功呢，是不是加载愿模型的前NLAYER层呢？

**Comment by t1101675** [comment]
是加载原模型的 NLAYER 层。相当于 pytorch 的 load_state_dict 的 strict 选项设置为了 false

**Comment by zhenhao-huang** [comment]
@t1101675 最近发现用`fp16`精度微调`chid`的`large`模型时，用`fp32`精度的配置文件`ds_finetune_large_fp32.json`可以加载到`32`层，并且在两张3090上每张显存占用只有`15`G大小，`loss`在第`50`个`global step`就收敛到二点几，这是没有启动`zero_optimizer`的原因吗？

**Comment by t1101675** [comment]
关于这个问题：内存减少不是因为 zero_optimizer 没有启动。内存减少的原因是：
一方面，相比于用 fp32 精度微调（即`finetune_chid_large_fp32.sh`）您指定了 `--fp16` 参数，导致在之后的计算中，所有浮点数确实以半精度计算，因此相比于 fp32 有内存减少。
另一方面，由于您使用了 deepspeed （即脚本中加入了 --deepspeed），程序使用 deepspeed 自带的一套 fp16 与 fp32 的训练方式。但是 `ds_finetune_large_fp32.json` 里面没有开启 deepspeed 的 fp16 选项，因此实际在训练时候的 deepspeed 并没有做在 optimizer 中维护 master_gradient 等额外操作，这些额外操作通常会占用一些显存，但也是保证训练收敛性与稳定性的重要部分（原因可见 https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html）。所以相比于用 fp16 精度的配置文件（ds_finetune_large.json），显存有所减少。

总结来说，内存减少的原因是您使用了半精度表示参数，同时没有开启半精度/混合精度训练需要的一些额外机制。我们没有试过用这种方法训练，但从 nvidia 关于 fp16 的文档来看，这样会存在一些问题，因此不推荐使用这种方法。

**Comment by zhenhao-huang** [comment]
@t1101675 明白了，会出现`nan`的错误，谢谢

**Comment by t1101675** [comment]
关于 CPU_offload，deepspeed 对于这个的支持目前只限于 fp16 的 zero-optimization stage 2。所以如果选择 fp32 训练，目前没有办法使用 CPU_offload 技术。

> cpu_offload 的这个问题我们也在尝试，之后有了明确的结论会及时更新

**Comment by zhenhao-huang** [comment]
@t1101675 在使用`fp16`情况下，我在`ds_finetune_large.json`的配置文件里的`zero_optimization`添加了`"cpu_offload": true`，结果显示`CPU Offload: True`启动成功，但是运行会报如下错误：

> Traceback (most recent call last):
  File "finetune_chid.py", line 371, in <module>
    main()
  File "finetune_chid.py", line 254, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "/home/klein/Desktop/CPM/CPM-Finetune/pretrain_gpt2.py", line 182, in setup_model_and_optimizer
    dist_init_required=False
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/__init__.py", line 118, in initialize
    config_params=config_params)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 181, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 609, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 749, in _configure_zero_optimizer
    gradient_accumulation_steps=self.gradient_accumulation_steps())
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 395, in __init__
    self.initialize_optimizer_states()
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 421, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 169, in step
    group['weight_decay'])
  File "/home/klein/anaconda3/lib/python3.6/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: expected input to be on cuda

这表示`apex`不支持`CPU_offload`吗，只能在`cuda`上运行？

**Comment by t1101675** [comment]
您需要在 `finetune_chid_large.sh` 中加入 `--cpu-optimizer` 参数

**Comment by zhenhao-huang** [comment]
选择`fp16`训练，`CPU_offload`成功启用后，可以跑到`32`层，结果是消耗大量的内存（几乎占满），在两张3090上每张显存大概占用了`12`g左右

**Comment by zhenhao-huang** [comment]
@t1101675 `32`层跑通后，我尝试增加到`65`层，可以跑通，每张显存也只占用了`17`g左右，看情况是可以继续往上增加...请问层数不是预先设计好的吗？CPM原模型的`32`层是根据什么设计的？

**Comment by t1101675** [comment]
如果增加层数，额外的层数只会被随机初始化。32 层是根据 GPT3 论文里面 GPT-3 2.7B 这个参数规模的模型配置定的
