### ISSUE TITLE
文本转id问题

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-Finetune#15]
微调的时候，我仔细看了下文本转id的结果，比如

> 可惜，现在布克赛季报销，而布莱切又回归了先发阵容。

在词表中对应的id是：

- "▁可": 112,
- "惜": 1989,
- "▁": 8,
- ",": 9,
- "▁现在": 129,
- "▁布": 3156,
- "克": 636,
- "赛": 639,
- "▁": 8,
- "季": 1388,
- "▁报": 2021,
- "销": 2530,
- "▁": 8,
- ",": 9,
- "▁而": 59,
- "布": 1765,
- "▁莱": 6221,
- "切": 2669,
- "▁又": 117,
- "▁回归": 5430,
- "▁了": 14,
- "▁先": 377,
- "发": 611,
- "▁阵容": 9892,
- "▁": 8,
- "。": 12,

连起来就是：

> ▁可惜▁,▁现在▁布克赛▁季▁报销▁,▁而布▁莱切▁又▁回归▁了▁先发▁阵容▁。
[112, 1989, 8, 9, 129, 3156, 636, 639, 8, 1388, 2021, 2530, 8, 9, 59, 1765, 6221, 2669, 117, 5430, 14, 377, 611, 9892, 8, 12]

1.请问下bpe分词转id都需要` ▁ `这个符号吗？这个导致我做微调时，文本转id生成了很多 `"▁": 8`即`"\u2581": 8`这个token，占用了输入训练的大部分长度。`"▁": 8`这个token部分是由`"▁现在": 129`类似的token拆分成两个，`"▁": 8`和`"现在": 11390`，`"▁可": 112`—>`"▁": 8`和`"可": 796`，这不会对训练有影响吗？
2.我观察了下每个token在词表都有对应的带`"▁": 8`符号token和单个token 比如`"▁可": 112` 和 `"可": 796`、`"▁现在": 129` 和 `"现在": 11390`，如果`"▁": 8`这个token不是必须的，为何不用单个token？

**Comment by lulu51230** [comment]
问题一我不知道怎么解释，对于问题二，所有词是按频率顺序排列的，"▁现在": 129 和 "现在": 11390这两个词，前面那个出现频率明显大很多，查表时较快。“_"我理解的是subword的意思，不知道理解到不到位。

**Comment by zzy14** [comment]
@zhenhao-huang 感谢您的问题。

1. 这里的 id 8 代表了分词产生的分隔符，原因是因为切词的时候先做了分词，分词后我们再用空格把词连起来，输到bpe里，比如你的例子，jieba会切成`['可惜', '，', '现在', '布克赛', '季', '报销', '，', '而布', '莱切', '又', '回归', '了', '先发', '阵容', '。']`，直接可以对应你连起来的那个句子。

2. "▁现在": 129 和 "现在": 11390在bpe看来是两种不同的token，比如jieba切出来一个词叫“现在不是”，那用的就是129，因为“现在”这时候一个词的开头，但如果是“不是现在”那么就应该选择11390。

**Comment by zhenhao-huang** [comment]
理解了，感谢解答
