### ISSUE TITLE
finetune_chid.py里面193~195行关于scores = torch.stack(tensor_list, 0).view(-1, 15000) 的含义？

### ISSUE THREAD

**Issue by lulu51230** [TsinghuaAI/CPM-Finetune#19]
当 model_parallel_size == 2 时，第195行代码为：scores = torch.stack(tensor_list, 0).view(-1, 15000)

如果将模型分成四份，在四块GPU上训练的话，则 model_parallel_size == 4 ？所以，
第195行代码是不是应该改为：scores = torch.stack(tensor_list, 0).view(-1, 7500)
我这样改过以后，仅使用前16层layers，训练第一个epoch约40%的数据时，evaluate dev ACC 已经达到 0.8147，感觉太高了,跟Readme里面给的数据不太一致。

想请问195行代码的含义到底是什么？

**Comment by t1101675** [comment]
195 行的含义是：将从各个**数据并行**的进程上 gather 过来的 tensor （存在 tensor_list 中）做成一个 tensor，然后整成 N * V 的 size，N是这一个 batch 里面样本的个数，V 是词表大小。
由于模型并行是2，全部词表大小是 30000，而这里只是 gather 了所有数据并行进程上的 tensor，所以最后词表那一维是 30000 / 2 =15000。这样做实际上用了一个 trick，也就是候选的10个 id 它们都小于 15000，所以可以只考虑词表的前半部分，从而减少一次 gather 的通信。

**Comment by t1101675** [comment]
我们试了一下用 model_parallel_size == 4 训练。把第195行代码改为 scores = torch.stack(tensor_list, 0).view(-1, 7500) 没有问题。我们用了全部层数，过了40%数据时候准确率是 64.6%，和我们之前 model_parallel_size == 2 的时候相似。你可以检查一下训练脚本里面是否将 MP 改成了4。如果还是不行，可以输出一下模型预测的结果，看下怎么样

**Comment by lulu51230** [comment]
您好，我确认我这边MP设为了4，您可以用前16层layer试一下吗？因为我这边训练过程中看起来一切正常。麻烦您啦。



---原始邮件---
发件人: "gyxbndsthu"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 下午4:44
收件人: "TsinghuaAI/CPM-Finetune"<CPM-Finetune@noreply.github.com&gt;;
抄送: "lulu51230"<834043584@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TsinghuaAI/CPM-Finetune] finetune_chid.py里面193~195行关于scores = torch.stack(tensor_list, 0).view(-1, 15000) 的含义？ (#19)




 
我们试了一下用 model_parallel_size == 4 训练。把第195行代码改为 scores = torch.stack(tensor_list, 0).view(-1, 7500) 没有问题。我们用了全部层数，过了40%数据时候准确率是 64.6%，和我们之前 model_parallel_size == 2 的时候相似。你可以检查一下训练脚本里面是否将 MP 改成了4。如果还是不行，可以输出一下模型预测的结果，看下怎么样

**Comment by t1101675** [comment]
我们也试了一下16层，过了40%数据后准确率是50.36%，感觉还比较正常。建议您输出一下模型 dev 集上面的预测结果，看一下是否正常

**Comment by lulu51230** [comment]
感谢您的回复！

这是 dev_log.txt , 我不太能看出来问题，
![image](https://user-images.githubusercontent.com/28756823/108321740-89f3fd80-71ff-11eb-9db7-cd06b88f5c0f.png)

我查看了一下我这边的参数，参数如下：
![image](https://user-images.githubusercontent.com/28756823/108322265-3cc45b80-7200-11eb-91ea-6378cf70c0df.png)

想请问你们在分布式训练时，有留下关于模型和数据混合并行的详细文档介绍么？

**Comment by t1101675** [comment]
请问您是否修改了 ds_finetune_large_fp32.json 文件？如果修改了能否也提供一下？

**Comment by lulu51230** [comment]
未曾修改ds_finetune_large_fp32.json文件。最近在排查另一个可能的错误，也没有能解决这个问题。

**Comment by lulu51230** [comment]
已排查出问题，我将batch设置为1，可能不符合数据模型混合并行，设置为4以后，dev_acc恢复正常。
