### ISSUE TITLE
[question] cand_ids变量的来源？

### ISSUE THREAD

**Issue by starkhu** [TsinghuaAI/CPM-Finetune#29]
finetune_chid.py文件中 CHIDDataset类的成员变量self.cand_ids。从注释上看该变量的含义是候选标签id，请教一下这个候选标签id是怎么生成的？

**Comment by t1101675** [comment]
这个 id 对应着词表里面的 ”0“，”1“， "2"，... ，”9“ 对应的 id

**Comment by starkhu** [comment]
好的，多谢。请教一下finetune_chid推理的逻辑，每一个输入都会配套10个成语吗？两个不同的输入但是它们的truth相同，这两个输入的成语是一样的还是不同的？

**Comment by t1101675** [comment]
每一个输入都会配套10个成语。和抱歉第二个问题没有太理解您的意思。只要 truth 相同，如果模型做对了的话，推理得到的就应该是相同的，但是做错了就不一定了。

**Comment by starkhu** [comment]
好的，多谢
