### ISSUE TITLE
请问后续有放出其他任务demo的计划吗

### ISSUE THREAD

**Issue by uk9921** [TsinghuaAI/CPM-Finetune#7]
完形填空预测的时候只需要计算原本句子的loss，但是其他任务（比如ner、分类等）计算loss的时候需要更复杂的操作，模版、类别候选词、few-shot context顺序都会极大的影响最后的准确率。请问repo中后续有更新更多样下游任务zero-shot、few-shot和finetune例子的计划吗？这些例子可以帮助使用者更好的理解cpm的能力边界。

**Comment by t1101675** [comment]
我们在此仓库中更新了 STC 对话任务的代码，同时 OCNLI，TNEWS，IFLYTEK 三个数据集的 zero-shot 测试也在 [CPM-Generate](https://github.com/TsinghuaAI/CPM-Generate) 仓库中更新了。
