### ISSUE TITLE
请问为什么微调代码里面没有model.zero_grad呢？难道不需要清空梯度吗？

### ISSUE THREAD

**Issue by keezen** [TsinghuaAI/CPM-Finetune#8]
https://github.com/TsinghuaAI/CPM-Finetune/blob/59d1d35254cf382bd6fa85f17062741cb4eb6803/finetune_chid.py#L295

**Comment by t1101675** [comment]
deepspeed 内部已经做了这件事情

**Comment by keezen** [comment]
> deepspeed 内部已经做了这件事情

理解了，谢谢~
