### ISSUE TITLE
在ChID数据集运行scripts/finetune_chid_large.sh报错

### ISSUE THREAD

**Issue by keezen** [TsinghuaAI/CPM-Finetune#9]
报错信息如下，请问finetune_child.py是经过测试过的没问题的吗，或者是cuda版本的问题？
```
Traceback (most recent call last):
  File "finetune_chid.py", line 372, in <module>
    main()
  File "finetune_chid.py", line 292, in main
    labels = (torch.sum(no_model_batch["labels"] * no_model_batch["loss_mask"], 1) / torch.sum(no_model_batch["loss_mask"], -1)).long()
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Long
```

**Comment by t1101675** [comment]
本地又测试了一下，是没有问题的。可能是 cuda 版本的问题。不过这里确实涉及到一个类型转换，刚刚已经修复为手动转换。

**Comment by zhenhao-huang** [comment]
跑scripts/finetune_chid_large.sh，我也报错了，这是什么原因
Traceback (most recent call last):
  File "finetune_chid.py", line 375, in <module>
    main()
  File "finetune_chid.py", line 292, in main
    output = model(**batch)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 854, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/model/distributed.py", line 78, in forward
    return self.module(*inputs, **kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/fp16/fp16.py", line 65, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/model/gpt2_modeling.py", line 97, in forward
    transformer_output = self.transformer(embeddings, attention_mask)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/mpu/transformer.py", line 416, in forward
    hidden_states = layer(hidden_states, attention_mask)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/mpu/transformer.py", line 294, in forward
    mlp_output = self.mlp(layernorm_output)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/klein/Desktop/CPM/CPM-Finetune/mpu/transformer.py", line 209, in forward
    intermediate_parallel = gelu(intermediate_parallel)
  File "/home/klein/Desktop/CPM/CPM-Finetune/mpu/transformer.py", line 166, in gelu
    return gelu_impl(x)
RuntimeError: default_program(56): error: identifier "aten_mul_flat__1" is undefined

default_program(57): error: no operator "=" matches these operands
            operand types are: half = float

default_program(61): error: identifier "aten_add_flat__1" is undefined

default_program(62): error: no operator "=" matches these operands
            operand types are: half = float

4 errors detected in the compilation of "default_program".

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}


#define __HALF_TO_US(var) *(reinterpret_cast<unsigned short *>(&(var)))
#define __HALF_TO_CUS(var) *(reinterpret_cast<const unsigned short *>(&(var)))
#if defined(__cplusplus)
  struct __align__(2) __half {
    __host__ __device__ __half() { }

  protected:
    unsigned short __x;
  };

  /* All intrinsic functions are only available to nvcc compilers */
  #if defined(__CUDACC__)
    /* Definitions of intrinsics */
    __device__ __half __float2half(const float f) {
      __half val;
      asm("{  cvt.rn.f16.f32 %0, %1;}\n" : "=h"(__HALF_TO_US(val)) : "f"(f));
      return val;
    }

    __device__ float __half2float(const __half h) {
      float val;
      asm("{  cvt.f32.f16 %0, %1;}\n" : "=f"(val) : "h"(__HALF_TO_CUS(h)));
      return val;
    }

  #endif /* defined(__CUDACC__) */
#endif /* defined(__cplusplus) */
#undef __HALF_TO_US
#undef __HALF_TO_CUS

typedef __half half;

extern "C" __global__
void func_1(half* t0, half* aten_mul_flat, half* aten_add_flat, half* aten_tanh_flat, half* aten_add_flat_1, half* aten_mul_flat_1, half* aten_mul_flat_2, half* aten_mul_flat_3) {
{
  float v = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  aten_mul_flat_1[512 * blockIdx.x + threadIdx.x] = __float2half(v * 0.04471499845385551f);
  float aten_mul_flat_ = __half2float(aten_mul_flat_2[512 * blockIdx.x + threadIdx.x]);
  aten_mul_flat__1 = __float2half(__half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]) * 0.7978845834732056f);
  aten_mul_flat_2[512 * blockIdx.x + threadIdx.x] = aten_mul_flat_;
  float v_1 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  aten_mul_flat_3[512 * blockIdx.x + threadIdx.x] = __float2half(v_1 * 0.5f);
  float aten_add_flat_ = __half2float(aten_add_flat_1[512 * blockIdx.x + threadIdx.x]);
  aten_add_flat__1 = __float2half((__half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]) * 0.04471499845385551f) * __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]) + 1.f);
  aten_add_flat_1[512 * blockIdx.x + threadIdx.x] = aten_add_flat_;
  float v_2 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_3 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_4 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  aten_tanh_flat[512 * blockIdx.x + threadIdx.x] = __float2half(tanhf((v_2 * 0.7978845834732056f) * ((v_3 * 0.04471499845385551f) * v_4 + 1.f)));
  float v_5 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_6 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_7 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  aten_add_flat[512 * blockIdx.x + threadIdx.x] = __float2half((tanhf((v_5 * 0.7978845834732056f) * ((v_6 * 0.04471499845385551f) * v_7 + 1.f))) + 1.f);
  float v_8 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_9 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_10 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  float v_11 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 5120 + 5120 * (((512 * blockIdx.x + threadIdx.x) / 5120) % 725)]);
  aten_mul_flat[512 * blockIdx.x + threadIdx.x] = __float2half((v_8 * 0.5f) * ((tanhf((v_9 * 0.7978845834732056f) * ((v_10 * 0.04471499845385551f) * v_11 + 1.f))) + 1.f));
}
}
